; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed=115200

lib_archive = false

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    askuric/Simple FOC @ ^2.3.2
    rfetick/MPU6050_light @ ^1.1.0
    adafruit/Adafruit BusIO @ ^1.16.1
    Wire
    SPIu
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
    ; asukiaaa/XboxSeriesXControllerESP32_asukiaaa
    ; asukiaaa/XboxControllerNotificationParser
    ; h2zero/NimBLE-Arduino